"""
Detection signals for Provenance Guard.

Signal 1: Groq LLM classifier (semantic signal)
Signal 2: Stylometric heuristics (structural signal) -- added in Milestone 4
"""

import os
import json
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LLM_PROMPT_TEMPLATE = """You are analyzing a piece of text to assess whether it was likely written by a human or generated by an AI language model.

Respond with ONLY a JSON object in this exact format, nothing else:
{{"ai_probability": <float between 0.0 and 1.0>, "reason": "<one sentence explanation>"}}

ai_probability should reflect how confident you are that the text is AI-generated:
- 0.0-0.2: very likely human-written
- 0.2-0.5: probably human, some AI-like qualities
- 0.5-0.8: probably AI, some human-like qualities
- 0.8-1.0: very likely AI-generated

Text to analyze:
---
{text}
---

Respond with ONLY the JSON object, no other text."""


def get_llm_signal(text: str) -> dict:
    """
    Signal 1: sends text to Groq and asks for a structured AI-probability judgment.

    Returns:
        {"score": float 0-1, "reason": str}

    Raises:
        RuntimeError if the API call fails or the response can't be parsed.
    """
    prompt = LLM_PROMPT_TEMPLATE.format(text=text)

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if the model wraps its JSON in them
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
        score = max(0.0, min(1.0, score))  # clamp to [0,1] just in case

        return {"score": score, "reason": parsed.get("reason", "")}

    except (json.JSONDecodeError, KeyError, ValueError) as e:
        raise RuntimeError(f"Failed to parse LLM signal response: {e}. Raw output: {raw!r}")
    except Exception as e:
        raise RuntimeError(f"Groq API call failed: {e}")


def get_stylometric_signal(text: str) -> dict:
    """
    Signal 2: pure-Python structural heuristics.
    Combines two metrics into a single 0-1 score where HIGHER = more AI-like.

    Metric 1 - sentence length variance: AI text trends toward uniform sentence
    lengths (low variance). We invert variance so low variance -> high score.

    Metric 2 - average word length: AI-generated text tends toward more
    Latinate, formal vocabulary (longer average word length) than casual
    human writing. NOTE: type-token ratio (vocabulary diversity) was tried
    here first, but testing showed raw TTR, root TTR (Guiraud's index), and
    Herdan's C all cluster near-identically (~0.86-0.97) across clearly-AI
    and clearly-human samples at this text length (40-55 words) -- the
    metric carries no signal until passages are much longer, regardless of
    which TTR variant is used. Average word length showed real separation
    on the same samples (6.23 vs 4.27 chars) and was substituted in instead.

    Returns:
        {"score": float 0-1, "sentence_variance": float, "avg_word_length": float}
    """
    import re

    # --- Metric 1: sentence length variance ---
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        # Not enough sentences to compute meaningful variance; treat as neutral
        norm_variance_score = 0.5
        raw_variance = None
    else:
        lengths = [len(s.split()) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        raw_variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        # Normalize: map variance to 0-1 then invert (low variance -> high AI-likeness)
        # Empirically, variance above ~40 is "high" (very human/irregular); cap there.
        capped = min(raw_variance, 40.0)
        norm_variance_score = 1.0 - (capped / 40.0)

    # --- Metric 2: average word length ---
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 5:
        norm_word_length_score = 0.5  # not enough words to be meaningful
        avg_word_length = None
    else:
        avg_word_length = sum(len(w) for w in words) / len(words)
        # Normalize across a realistic band: ~4.0 chars (casual/conversational)
        # to ~7.0 chars (formal/technical). Higher -> more AI-like.
        norm_word_length_score = max(0.0, min(1.0, (avg_word_length - 4.0) / 3.0))

    stylometric_score = round(0.5 * norm_variance_score + 0.5 * norm_word_length_score, 3)

    return {
        "score": stylometric_score,
        "sentence_variance": raw_variance,
        "avg_word_length": avg_word_length,
    }


def get_combined_confidence(llm_score: float, stylometric_score: float) -> float:
    """Combines both signals per planning.md: 0.6 LLM + 0.4 stylometric."""
    return round(0.6 * llm_score + 0.4 * stylometric_score, 3)


def score_to_attribution(confidence: float) -> str:
    """Maps combined confidence to one of the three buckets."""
    if confidence < 0.35:
        return "likely_human"
    elif confidence < 0.70:
        return "uncertain"
    else:
        return "likely_ai"


if __name__ == "__main__":
    # Quick manual test -- run `python signals.py` to sanity check both signals
    # and combined scoring before wiring into Flask.
    test_inputs = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in modern society. "
            "It is important to note that while the benefits of AI are numerous, it is equally "
            "essential to consider the ethical implications. Furthermore, stakeholders across "
            "various sectors must collaborate to ensure responsible deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after. my friend got the spicy version and "
            "said it was better. probably won't go back unless someone drags me there"
        ),
        "borderline_formal_human": (
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental tension "
            "between their mandate for price stability and the unintended consequences of "
            "prolonged low interest rates on equity and real estate valuations."
        ),
        "borderline_edited_ai": (
            "I've been thinking a lot about remote work lately. There are genuine tradeoffs — "
            "flexibility and no commute on one side, isolation and blurred work-life boundaries "
            "on the other. Studies show productivity varies widely by individual and role type."
        ),
    }

    for label, text in test_inputs.items():
        llm_result = get_llm_signal(text)
        style_result = get_stylometric_signal(text)
        combined = get_combined_confidence(llm_result["score"], style_result["score"])
        bucket = score_to_attribution(combined)

        print(f"--- {label} ---")
        print(f"  llm_score:         {llm_result['score']:.2f}  ({llm_result['reason']})")
        print(f"  stylometric_score: {style_result['score']:.2f}  "
              f"(sentence_variance={style_result['sentence_variance']}, "
              f"avg_word_length={style_result['avg_word_length']})")
        print(f"  combined_score:    {combined:.2f}  -> {bucket}")
        print()